/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RepositoryOwnerRepoImport } from './routes/repository/$owner.$repo'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RepositoryOwnerRepoRoute = RepositoryOwnerRepoImport.update({
  id: '/repository/$owner/$repo',
  path: '/repository/$owner/$repo',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/repository/$owner/$repo': {
      id: '/repository/$owner/$repo'
      path: '/repository/$owner/$repo'
      fullPath: '/repository/$owner/$repo'
      preLoaderRoute: typeof RepositoryOwnerRepoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/repository/$owner/$repo': typeof RepositoryOwnerRepoRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/repository/$owner/$repo': typeof RepositoryOwnerRepoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/repository/$owner/$repo': typeof RepositoryOwnerRepoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/repository/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repository/$owner/$repo'
  id: '__root__' | '/' | '/repository/$owner/$repo'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RepositoryOwnerRepoRoute: typeof RepositoryOwnerRepoRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RepositoryOwnerRepoRoute: RepositoryOwnerRepoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/repository/$owner/$repo"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/repository/$owner/$repo": {
      "filePath": "repository/$owner.$repo.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
